spring:
  application:
    name: stock-service

server:
  port: 8301


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

zuul:
  host:
    connect-timeout-millis: 600000 # starting the connection 
    socket-timeout-millis: 600000  # monitor the continuous incoming data flow